import type { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    price: 25000,
    mileage: 15000,
    location: 'Lagos, Nigeria',
    bodyType: 'Sedan',
    engine: '2.5L 4-Cylinder',
    transmission: 'Automatic',
    exteriorColor: 'White',
    interiorColor: 'Black',
    features: ['Bluetooth', 'Backup Camera', 'Apple CarPlay', 'Lane Assist'],
    images: ['sedan-1', 'sedan-2', 'sedan-3'],
    description: "A reliable and stylish sedan, the 2022 Toyota Camry offers a smooth ride, excellent fuel economy, and a spacious interior. Perfect for families and commuters alike, it comes packed with modern safety features.",
    status: 'Available',
  },
  {
    id: '2',
    make: 'Ford',
    model: 'F-150',
    year: 2021,
    price: 38000,
    mileage: 22000,
    location: 'Abuja, Nigeria',
    bodyType: 'Truck',
    engine: '3.5L V6 EcoBoost',
    transmission: 'Automatic',
    exteriorColor: 'Red',
    interiorColor: 'Gray',
    features: ['Towing Package', '4x4', 'Touchscreen Display', 'Bed Liner'],
    images: ['truck-1', 'truck-2', 'truck-3'],
    description: "The 2021 Ford F-150 is the king of trucks. With its powerful EcoBoost engine and rugged 4x4 capabilities, it's ready for any job site or weekend adventure. The spacious cabin ensures a comfortable journey no matter the destination.",
    status: 'Available',
  },
  {
    id: '3',
    make: 'Honda',
    model: 'CR-V',
    year: 2023,
    price: 32000,
    mileage: 5000,
    location: 'Port Harcourt, Nigeria',
    bodyType: 'SUV',
    engine: '1.5L Turbo 4-Cylinder',
    transmission: 'CVT',
    exteriorColor: 'Black',
    interiorColor: 'Tan',
    features: ['Sunroof', 'Heated Seats', 'Honda Sensing', 'All-Wheel Drive'],
    images: ['suv-1', 'suv-2', 'suv-3'],
    description: "This nearly-new 2023 Honda CR-V is the ideal compact SUV. It boasts a fuel-efficient turbocharged engine, confident all-wheel-drive handling, and Honda's suite of advanced safety features. A perfect blend of practicality and comfort.",
    status: 'Pending',
  },
  {
    id: '4',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2020,
    price: 42000,
    mileage: 30000,
    location: 'Lagos, Nigeria',
    bodyType: 'Luxury Sedan',
    engine: '2.0L Turbo 4-Cylinder',
    transmission: 'Automatic',
    exteriorColor: 'Silver',
    interiorColor: 'Red',
    features: ['Leather Seats', 'Burmester Sound System', 'Ambient Lighting', 'Navigation'],
    images: ['luxury-1', 'luxury-2', 'luxury-3'],
    description: "Experience true luxury with the 2020 Mercedes-Benz C-Class. This sedan combines elegant styling with sporty performance. The striking red leather interior and premium Burmester audio system create an unparalleled driving environment.",
    status: 'Sold',
  },
    {
    id: '5',
    make: 'BMW',
    model: '4 Series Convertible',
    year: 2022,
    price: 55000,
    mileage: 9000,
    location: 'Lagos, Nigeria',
    bodyType: 'Convertible',
    engine: '2.0L Turbo 4-Cylinder',
    transmission: 'Automatic',
    exteriorColor: 'Blue',
    interiorColor: 'White',
    features: ['Heads-Up Display', 'Harman Kardon Sound', 'Heated Steering Wheel'],
    images: ['convertible-1', 'luxury-2', 'luxury-3'],
    description: "Feel the wind in your hair with this stunning 2022 BMW 4 Series Convertible. Its powerful engine and agile handling deliver BMW's signature ultimate driving experience. Perfect for sunny days and coastal drives.",
    status: 'Available',
  },
  {
    id: '6',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 48000,
    mileage: 12000,
    location: 'Abuja, Nigeria',
    bodyType: 'Electric Sedan',
    engine: 'Electric',
    transmission: 'Automatic',
    exteriorColor: 'White',
    interiorColor: 'Black',
    features: ['Autopilot', 'Full Glass Roof', '15-inch Touchscreen', 'Premium Connectivity'],
    images: ['electric-1', 'sedan-2', 'sedan-3'],
    description: "Join the electric revolution with the 2023 Tesla Model 3. Enjoy instant acceleration, cutting-edge technology with Autopilot, and zero emissions. This vehicle represents the future of driving.",
    status: 'Available',
  }
];

export function getVehicles() {
  return vehicles;
}

export function getVehicleById(id: string) {
  return vehicles.find(v => v.id === id);
}

export function getFeaturedVehicles(count: number) {
  return vehicles.filter(v => v.status === 'Available').slice(0, count);
}
